config/routes.rb
Tradr::Application.routes.draw do
root :to => 'home#index'
resources :users, :only => [:index, :new, :create, :delete]

get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

resources :stocks

end

app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id             :integer          not null, primary key
#  symbol         :string(255)
#  shares         :integer
#  purchase_price :decimal(, )
#  user_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Stock < ActiveRecord::Base
  attr_accessible :symbol, :shares, :purchase_price
  belongs_to :user, :inverse_of => :stocks
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  password_digest :string(255)
#  balance         :decimal(, )
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :balance, :password, :password_confirmation
  has_many :stocks, :inverse_of => :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def index
      if user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to(users_path)
        respond_to do |format|
          format.js {render :create}
        end
      else
        redirect_to(login_path)
      end
    end

    def new
    end

    def create
      user = User.where(:email => params[:email]).first
      if user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to(stocks_path)
      else
        redirect_to(login_path)
      end
    end
    def destroy
      session[:user_id] = nil
      redirect_to(root_path)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  # before_filter :logged_in_view

  def index
  end

  def stock
  @stock = params[:symbol]
    @stock = @stock.upcase
    @quote = YahooFinance::get_quotes(YahooFinance::StandardQuote, @stock)[@stock].lastTrade
    @everything = YahooFinance::get_quotes(YahooFinance::StandardQuote, @stock)[@stock]
    @name = YahooFinance::get_quotes(YahooFinance::StandardQuote, @stock)[@stock].name
    @change = YahooFinance::get_quotes(YahooFinance::StandardQuote, @stock)[@stock].changePercent
  end

  private
  def logged_in_view
    if @auth.nil?
      redirect_to(root_path)
      print("You are not logged in")
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
      @user = User.new
      # respond_to do |format|
      #   format.html { redirect_to(users_path) }
      #   format.js { render :new }
      # end
    end

    def create
      user = User.create(params[:user])
      session[:user_id] = user.id
      @users = User.order(:email)
      # what does line 14 do?
      respond_to do |format|
      format.js {render :create}
      end
    end

    def index
      @users=User.all
    end

    private
  def logged_in_view
    if @auth.nil?
      redirect_to(root_path)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_users.html.haml
- @users.each do |user|
  %li user.name
  %li user.balance

app/views/home/index.html.haml
%div.row
  %div.main-box.large-12.columns
    %ol
      %h1 BulltradR.
      %h3 for Bullish Investors
%div#landing
%div#new_user

app/views/layouts/_nav.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="nav-bar right">
      <ul class="button-group">
        <li><%= link_to('Sign Up', new_user_path, :remote => true, :class => 'button') %></li>
        <li><%= link_to('Sign In', login_path, :class => 'button') %></li>
      <li><%= link_to('Bull Info', users_path,:class => 'button') %></li>
      <li><%= link_to('Portfolio & Bank Data', stocks_path,:class => 'button') %></li>
      <li><%= link_to('Logout', login_path,:method=>:delete, :class => 'button') %></li>
    </ul>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>WELCOME TO Tradr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "vendor/custom.modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
<%=render :partial => 'layouts/nav' %>
</header>
<%= yield %>
</body>
</html>

app/views/session/new.html.haml
%div.row
  %div.large-3.columns
    = form_tag '/login' do
      = label_tag :email
      = text_field_tag :email, nil, :autofocus => true
      = label_tag :password
      = password_field_tag :password
      = submit_tag 'Login', :class => 'button radius'
  %div.large-9.columns

app/views/stocks/_form.html.erb
<form class = "custom">
  <div class= "row">
      <div class="large-6 columns">
      </div>
      <h3>Quote Manager</h3>
      <div class="row collapse">
        <div class="large-12 small-12 columns">
          <input type="text" placeholder="QUOTECODE"/>
        <input type="integer" placeholder="NUMBER OF SHARES" />
        <ul class="button-group">
          <li><%= link_to('quote', new_stock_path, :class => 'button') %></li>
          <li><%= link_to('buy', new_stock_path, :class => 'button') %></li>
          <li><%= link_to('sell', new_stock_path, :class => 'button') %></li>
        </ul>
                </div>
      </div>

  </div>
</form>

app/views/stocks/_view.html.erb
<h1>Stock Portfolio</h1>
<div id="chart"></div>

app/views/stocks/index.html.erb
<div class="row">
  <div class="small-3 columns">
    <div id="menu">
      <div class="section-container vertical-nav" data-section>
        <section>
          <h2 class="title" data-section-title><a href="#">Bank Data</a></h2>
            <div class="title" data-section-title>
              <p>Balance: $ </p>
              <p>Portfolio Value: $ </p>
              <p>Change in Portfolio Value: $ </p>
            </div>
        </section>
      </div>
    </div>
    <div id="form">
      <%=render :partial => 'stocks/form' %>
    </div>
  </div>
  <div class="small-9 columns">
    <div id="list">
    </div>
    <%=render :partial => 'stocks/view' %>
  </div>
</div>

app/views/stocks/index.js.erb
$(document).ready(function(){

  $('#graphic').on('click', function() {
    $('#chart').empty().append('<%=j render (:partial => 'form')%>');
});

function process_activity(activities){
  new Morris.Line({
    // ID of the element in which to draw the chart.
    element: 'chart',
    // Chart data records -- each entry in this array corresponds to a point on
    // the chart.
    data: [
      { year: '2008', value: 10 },
      { year: '2009', value: 30 },
      { year: '2010', value: 5 },
      { year: '2011', value: 20 },
      { year: '2012', value: 10 }

          ],
    // The name of the data record attribute that contains x-values.
    xkey: 'year',
    // A list of names of data record attributes that contain y-values.
    ykeys: ['value'],
    // Labels for the ykeys -- will be displayed when you hover over the
    // chart.
    labels: ['Value']
  });
}

if ($('#chart').length > 0) {process_activity() };

});

app/views/users/_form.html.haml
%div.row#form
  %div.large-11.columns
    = form_for @user, :remote => true do |f|
      = f.label :email
      = f.text_field :email, :autofocus => true
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = f.submit nil, :class => 'button radius'
  %div.large-1.columns

app/views/users/create.js.erb
location.reload();

app/views/users/index.html.haml
/ = render :partial => 'index'
%tr
  %th email
  %th cash
  %th position
  %th total
  = @users.each do |user|
    %tr
      %td=user.email
      %td=number_to_currency(user.balance)
      / / %td=number_to_currency(user.position)
      / %td=number_to_currency(user.total)

app/views/users/index.js.erb
$('#new_user').html('<%=j render (:partial => 'index')  %>');

app/views/users/new.html.haml
%div#new_user
Gday World

app/views/users/new.js.erb
$('#new_user').html('<%=j render(:partial => 'form') %>');